### ISSUE TITLE
Some fields with resolvers incorrectly return nullable false

### ISSUE THREAD

**Issue by miksgailis** [guntiso/mojoz#3]
Metadata call incorrectly shows resolvable codifier field as not nullable even if it should be nullable. Other types of resolvers seems to be working fine but in cases like these nullable is always returned as false.

Example:
	example = example.title -> =  codif_id('EXAMPLE', _)

Metadata:
	codifType: "EXAMPLE"
	comments: null
	enum: null
	insertable: true
	isCollection: false
	isComplexType: false
	jsonType: "string"
	label: "Example"
	length: 1000
	name: "example"
	nullable: false
	refViewName: null
	required: false
	sortable: false
	type: "string"
	updatable: true
	visible: true

**Comment by guntiso** [comment]
Fixed in v4.0.0, commit f873fb08
